name: Create and store bundle file for current API version

on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest

    env:
      INDEX_FILE: specification/gridtariffapi.json
      ARTIFACT_PREFIX: gridtariffapi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenAPI CLI and jq
        run: |
          npm install -g @redocly/openapi-cli
          sudo apt-get install -y jq

      - name: Extract OpenAPI Version
        id: get_version
        run: |
          VERSION=$(jq -r '.info.version' $INDEX_FILE)
          echo "Extracted OpenAPI version: $VERSION"
          echo "OPENAPI_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate OpenAPI Bundle
        run: |
          mkdir -p specification/versions
          NEW_BUNDLE_FILE="specification/versions/gridtariffapi-v$OPENAPI_VERSION.json"
          echo "Bundling OpenAPI specification to $NEW_BUNDLE_FILE"
          openapi bundle $INDEX_FILE -o $NEW_BUNDLE_FILE
          echo "BUNDLE_FILE=$NEW_BUNDLE_FILE" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Create new bundle file for API version ${{ env.OPENAPI_VERSION }}
          commiter: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: gh-action/bundle-and-store-api-version
          delete-branch: true
          title: Add bundle file for API version ${{ env.OPENAPI_VERSION }}
