name: Create release on existing tag

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing tag (e.g. v1.2.3)'
        required: true
        type: string

permissions:
  contents: write # needed to create release

env:
  OPENAPI_ENTRY: specification/gridtariffapi.json
  OUT_DIR: dist
  BUNDLED_JSON: dist/openapi.json
  REDOC_HTML: dist/redoc.html

jobs:
  release:
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name matches '^v\\d+\\.\\d+\\.\\d+$')
      || (github.event_name == 'workflow_dispatch')

    runs-on: ubuntu-latest
    env:
      TAG: "${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}"
      VERSION: "${TAG#v}"

    steps:
      - name: Check out tag ref
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Bundle OpenAPI
        run: |
          mkdir -p "$OUT_DIR"
          npx --yes @redocly/cli@latest bundle "$OPENAPI_ENTRY" \
            --output "$BUNDLED_JSON" \
            --ext json

      - name: Lint OpenAPI (bundled)
        run: npx --yes @redocly/cli@latest lint "$BUNDLED_JSON"

      - name: Verify info.version matches tag
        run: |
          FILE_VER=$(jq -r '.info.version' $BUNDLED_JSON)
          if [ "$FILE_VER" != "$VERSION" ]; then
            echo "info.version ($FILE_VER) does not match input version ($VERSION)"
            exit 1
          fi

      - name: Build Redoc HTML
        run: npx --yes @redocly/cli@latest build-docs "$BUNDLED_JSON" --output="$REDOC_HTML"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          body: |
            Automated release for ${{ env.TAG }}.

            - Linted source OpenAPI (`${{ env.OPENAPI_ENTRY }}`)
            - Bundled to `${{ env.BUNDLED_JSON }}`
            - Generated Redoc `${{ env.REDOC_HTML }}`
          files: |
            dist/openapi.json
            dist/redoc.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # (Nice to have) Upload the files as workflow run artifacts as well
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi-release-${{ steps.validate.outputs.tag }}
          path: |
            dist/openapi.json
            dist/redoc.html
